language: python

python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

env:
  - DJANGO="Django==2.0.*"
  - DJANGO="Django==1.11.*"
  - DJANGO="Django==1.10.*"
  - DJANGO="Django==1.9.*"
  - DJANGO="Django==1.8.*"
  - DJANGO="Django==1.7.*"

install:
  - pip install -U coverage coveralls $DJANGO
  
script: coverage run -a --source=logexpose logexpose/runtests.py

matrix:

  exclude:
   - python: 3.6
     env: DJANGO="Django==1.7.*"

   - python: 3.5
     env: DJANGO="Django==1.7.*"

   - python: 2.7
     env: DJANGO="Django==2.0.*"


after_success:
  coveralls
